# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import grid_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='gridadmin.proto',
  package='',
  serialized_pb='\n\x0fgridadmin.proto\x1a\ngrid.proto\"8\n\x13IncomingPacketProxy\x12\x11\n\tsessionId\x18\x01 \x02(\x03\x12\x0e\n\x06packet\x18\x03 \x02(\x0c\"1\n\x0bPacketProxy\x12\x12\n\nsessionIds\x18\x01 \x03(\x03\x12\x0e\n\x06packet\x18\x02 \x02(\x0c\"+\n\x16\x41uthorizationChallenge\x12\x11\n\tchallenge\x18\x01 \x02(\t\"7\n\x14\x41uthorizationRequest\x12\r\n\x05login\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"(\n\x15\x41uthorizationResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\"\x16\n\x14ReportClientsRequest\"\x88\x01\n\x15ReportClientsResponse\x12.\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x1d.ReportClientsResponse.Client\x1a?\n\x06\x43lient\x12\x11\n\tsessionId\x18\x01 \x02(\x03\x12\x11\n\tmachineId\x18\x02 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x02(\t\"P\n\x10\x41\x64minPacketProxy\x12\x0f\n\x07\x65nabled\x18\x01 \x02(\x08\x12\x1b\n\x13\x65nabledForSessionId\x18\x02 \x01(\x03\x12\x0e\n\x06\x65vents\x18\x03 \x02(\x08\"G\n\x0e\x41\x64minNewClient\x12\x11\n\tsessionId\x18\x01 \x02(\x03\x12\x11\n\tmachineId\x18\x02 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x02(\t\"*\n\x15\x41\x64minClientDisconnect\x12\x11\n\tsessionId\x18\x01 \x02(\x03')




_INCOMINGPACKETPROXY = descriptor.Descriptor(
  name='IncomingPacketProxy',
  full_name='IncomingPacketProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sessionId', full_name='IncomingPacketProxy.sessionId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packet', full_name='IncomingPacketProxy.packet', index=1,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=87,
)


_PACKETPROXY = descriptor.Descriptor(
  name='PacketProxy',
  full_name='PacketProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sessionIds', full_name='PacketProxy.sessionIds', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packet', full_name='PacketProxy.packet', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=138,
)


_AUTHORIZATIONCHALLENGE = descriptor.Descriptor(
  name='AuthorizationChallenge',
  full_name='AuthorizationChallenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='challenge', full_name='AuthorizationChallenge.challenge', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=140,
  serialized_end=183,
)


_AUTHORIZATIONREQUEST = descriptor.Descriptor(
  name='AuthorizationRequest',
  full_name='AuthorizationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='login', full_name='AuthorizationRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='AuthorizationRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=185,
  serialized_end=240,
)


_AUTHORIZATIONRESPONSE = descriptor.Descriptor(
  name='AuthorizationResponse',
  full_name='AuthorizationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='success', full_name='AuthorizationResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=242,
  serialized_end=282,
)


_REPORTCLIENTSREQUEST = descriptor.Descriptor(
  name='ReportClientsRequest',
  full_name='ReportClientsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=284,
  serialized_end=306,
)


_REPORTCLIENTSRESPONSE_CLIENT = descriptor.Descriptor(
  name='Client',
  full_name='ReportClientsResponse.Client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sessionId', full_name='ReportClientsResponse.Client.sessionId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='machineId', full_name='ReportClientsResponse.Client.machineId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='ReportClientsResponse.Client.address', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=382,
  serialized_end=445,
)

_REPORTCLIENTSRESPONSE = descriptor.Descriptor(
  name='ReportClientsResponse',
  full_name='ReportClientsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clients', full_name='ReportClientsResponse.clients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REPORTCLIENTSRESPONSE_CLIENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=309,
  serialized_end=445,
)


_ADMINPACKETPROXY = descriptor.Descriptor(
  name='AdminPacketProxy',
  full_name='AdminPacketProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='enabled', full_name='AdminPacketProxy.enabled', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enabledForSessionId', full_name='AdminPacketProxy.enabledForSessionId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='events', full_name='AdminPacketProxy.events', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=447,
  serialized_end=527,
)


_ADMINNEWCLIENT = descriptor.Descriptor(
  name='AdminNewClient',
  full_name='AdminNewClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sessionId', full_name='AdminNewClient.sessionId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='machineId', full_name='AdminNewClient.machineId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='AdminNewClient.address', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=529,
  serialized_end=600,
)


_ADMINCLIENTDISCONNECT = descriptor.Descriptor(
  name='AdminClientDisconnect',
  full_name='AdminClientDisconnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sessionId', full_name='AdminClientDisconnect.sessionId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=602,
  serialized_end=644,
)

_REPORTCLIENTSRESPONSE_CLIENT.containing_type = _REPORTCLIENTSRESPONSE;
_REPORTCLIENTSRESPONSE.fields_by_name['clients'].message_type = _REPORTCLIENTSRESPONSE_CLIENT
DESCRIPTOR.message_types_by_name['IncomingPacketProxy'] = _INCOMINGPACKETPROXY
DESCRIPTOR.message_types_by_name['PacketProxy'] = _PACKETPROXY
DESCRIPTOR.message_types_by_name['AuthorizationChallenge'] = _AUTHORIZATIONCHALLENGE
DESCRIPTOR.message_types_by_name['AuthorizationRequest'] = _AUTHORIZATIONREQUEST
DESCRIPTOR.message_types_by_name['AuthorizationResponse'] = _AUTHORIZATIONRESPONSE
DESCRIPTOR.message_types_by_name['ReportClientsRequest'] = _REPORTCLIENTSREQUEST
DESCRIPTOR.message_types_by_name['ReportClientsResponse'] = _REPORTCLIENTSRESPONSE
DESCRIPTOR.message_types_by_name['AdminPacketProxy'] = _ADMINPACKETPROXY
DESCRIPTOR.message_types_by_name['AdminNewClient'] = _ADMINNEWCLIENT
DESCRIPTOR.message_types_by_name['AdminClientDisconnect'] = _ADMINCLIENTDISCONNECT

class IncomingPacketProxy(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INCOMINGPACKETPROXY
  
  # @@protoc_insertion_point(class_scope:IncomingPacketProxy)

class PacketProxy(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKETPROXY
  
  # @@protoc_insertion_point(class_scope:PacketProxy)

class AuthorizationChallenge(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHORIZATIONCHALLENGE
  
  # @@protoc_insertion_point(class_scope:AuthorizationChallenge)

class AuthorizationRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHORIZATIONREQUEST
  
  # @@protoc_insertion_point(class_scope:AuthorizationRequest)

class AuthorizationResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHORIZATIONRESPONSE
  
  # @@protoc_insertion_point(class_scope:AuthorizationResponse)

class ReportClientsRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPORTCLIENTSREQUEST
  
  # @@protoc_insertion_point(class_scope:ReportClientsRequest)

class ReportClientsResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Client(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPORTCLIENTSRESPONSE_CLIENT
    
    # @@protoc_insertion_point(class_scope:ReportClientsResponse.Client)
  DESCRIPTOR = _REPORTCLIENTSRESPONSE
  
  # @@protoc_insertion_point(class_scope:ReportClientsResponse)

class AdminPacketProxy(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADMINPACKETPROXY
  
  # @@protoc_insertion_point(class_scope:AdminPacketProxy)

class AdminNewClient(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADMINNEWCLIENT
  
  # @@protoc_insertion_point(class_scope:AdminNewClient)

class AdminClientDisconnect(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADMINCLIENTDISCONNECT
  
  # @@protoc_insertion_point(class_scope:AdminClientDisconnect)

# @@protoc_insertion_point(module_scope)
