# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appwindow.ui'
#
# Created: Sun Jun  5 11:44:26 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(716, 701)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clientList = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientList.sizePolicy().hasHeightForWidth())
        self.clientList.setSizePolicy(sizePolicy)
        self.clientList.setObjectName(_fromUtf8("clientList"))
        self.horizontalLayout.addWidget(self.clientList)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.clientPage = QtGui.QWidget()
        self.clientPage.setObjectName(_fromUtf8("clientPage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.clientPage)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.clientTabWidget = QtGui.QTabWidget(self.clientPage)
        self.clientTabWidget.setEnabled(True)
        self.clientTabWidget.setObjectName(_fromUtf8("clientTabWidget"))
        self.infoTab = QtGui.QWidget()
        self.infoTab.setObjectName(_fromUtf8("infoTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.infoTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.infoTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.clientVersion = QtGui.QLabel(self.groupBox_4)
        self.clientVersion.setObjectName(_fromUtf8("clientVersion"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.clientVersion)
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.machineId = QtGui.QLabel(self.groupBox_4)
        self.machineId.setObjectName(_fromUtf8("machineId"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.machineId)
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_26)
        self.sessionId = QtGui.QLabel(self.groupBox_4)
        self.sessionId.setObjectName(_fromUtf8("sessionId"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sessionId)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.infoTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.system = QtGui.QLabel(self.groupBox)
        self.system.setObjectName(_fromUtf8("system"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.system)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.node = QtGui.QLabel(self.groupBox)
        self.node.setObjectName(_fromUtf8("node"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.node)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.release = QtGui.QLabel(self.groupBox)
        self.release.setObjectName(_fromUtf8("release"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.release)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.version = QtGui.QLabel(self.groupBox)
        self.version.setObjectName(_fromUtf8("version"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.version)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.machine = QtGui.QLabel(self.groupBox)
        self.machine.setObjectName(_fromUtf8("machine"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.machine)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_18)
        self.processor = QtGui.QLabel(self.groupBox)
        self.processor.setObjectName(_fromUtf8("processor"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.processor)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.infoTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.memoryFree = QtGui.QLabel(self.groupBox_2)
        self.memoryFree.setObjectName(_fromUtf8("memoryFree"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.memoryFree)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.totalMemory = QtGui.QLabel(self.groupBox_2)
        self.totalMemory.setObjectName(_fromUtf8("totalMemory"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.totalMemory)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.cpuUsage = QtGui.QLabel(self.groupBox_2)
        self.cpuUsage.setObjectName(_fromUtf8("cpuUsage"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.cpuUsage)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.diskFree = QtGui.QLabel(self.groupBox_2)
        self.diskFree.setObjectName(_fromUtf8("diskFree"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.diskFree)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_24)
        self.actualTime = QtGui.QLabel(self.groupBox_2)
        self.actualTime.setObjectName(_fromUtf8("actualTime"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.actualTime)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.clientTabWidget.addTab(self.infoTab, _fromUtf8(""))
        self.jobsTab = QtGui.QWidget()
        self.jobsTab.setObjectName(_fromUtf8("jobsTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.jobsTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.jobsClientList = QtGui.QTableWidget(self.jobsTab)
        self.jobsClientList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.jobsClientList.setTabKeyNavigation(False)
        self.jobsClientList.setProperty(_fromUtf8("showDropIndicator"), False)
        self.jobsClientList.setDragDropOverwriteMode(True)
        self.jobsClientList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.jobsClientList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.jobsClientList.setShowGrid(False)
        self.jobsClientList.setCornerButtonEnabled(True)
        self.jobsClientList.setObjectName(_fromUtf8("jobsClientList"))
        self.jobsClientList.setColumnCount(2)
        self.jobsClientList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.jobsClientList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.jobsClientList.setHorizontalHeaderItem(1, item)
        self.jobsClientList.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.jobsClientList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startClientJob = QtGui.QPushButton(self.jobsTab)
        self.startClientJob.setEnabled(False)
        self.startClientJob.setObjectName(_fromUtf8("startClientJob"))
        self.horizontalLayout_2.addWidget(self.startClientJob)
        self.stopClientJob = QtGui.QPushButton(self.jobsTab)
        self.stopClientJob.setEnabled(False)
        self.stopClientJob.setObjectName(_fromUtf8("stopClientJob"))
        self.horizontalLayout_2.addWidget(self.stopClientJob)
        self.removeClientJob = QtGui.QPushButton(self.jobsTab)
        self.removeClientJob.setEnabled(False)
        self.removeClientJob.setObjectName(_fromUtf8("removeClientJob"))
        self.horizontalLayout_2.addWidget(self.removeClientJob)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.newClientJob = QtGui.QPushButton(self.jobsTab)
        self.newClientJob.setObjectName(_fromUtf8("newClientJob"))
        self.horizontalLayout_2.addWidget(self.newClientJob)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.clientTabWidget.addTab(self.jobsTab, _fromUtf8(""))
        self.actionsTab = QtGui.QWidget()
        self.actionsTab.setObjectName(_fromUtf8("actionsTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.actionsTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.closeClient = QtGui.QCommandLinkButton(self.actionsTab)
        self.closeClient.setObjectName(_fromUtf8("closeClient"))
        self.verticalLayout_5.addWidget(self.closeClient)
        self.shutdownClient = QtGui.QCommandLinkButton(self.actionsTab)
        self.shutdownClient.setObjectName(_fromUtf8("shutdownClient"))
        self.verticalLayout_5.addWidget(self.shutdownClient)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.clientTabWidget.addTab(self.actionsTab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.clientTabWidget)
        self.stackedWidget.addWidget(self.clientPage)
        self.gridPage = QtGui.QWidget()
        self.gridPage.setObjectName(_fromUtf8("gridPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gridPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridTabWidget = QtGui.QTabWidget(self.gridPage)
        self.gridTabWidget.setObjectName(_fromUtf8("gridTabWidget"))
        self.info = QtGui.QWidget()
        self.info.setObjectName(_fromUtf8("info"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.info)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_3 = QtGui.QGroupBox(self.info)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.serverHost = QtGui.QLabel(self.groupBox_3)
        self.serverHost.setObjectName(_fromUtf8("serverHost"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.serverHost)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.clientCount = QtGui.QLabel(self.groupBox_3)
        self.clientCount.setObjectName(_fromUtf8("clientCount"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.clientCount)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.gridTabWidget.addTab(self.info, _fromUtf8(""))
        self.actionsTab1 = QtGui.QWidget()
        self.actionsTab1.setObjectName(_fromUtf8("actionsTab1"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.actionsTab1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.serverJobList = QtGui.QTableWidget(self.actionsTab1)
        self.serverJobList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.serverJobList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.serverJobList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.serverJobList.setObjectName(_fromUtf8("serverJobList"))
        self.serverJobList.setColumnCount(2)
        self.serverJobList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.serverJobList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.serverJobList.setHorizontalHeaderItem(1, item)
        self.serverJobList.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.serverJobList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.startServerJob = QtGui.QPushButton(self.actionsTab1)
        self.startServerJob.setEnabled(False)
        self.startServerJob.setObjectName(_fromUtf8("startServerJob"))
        self.horizontalLayout_3.addWidget(self.startServerJob)
        self.stopServerJob = QtGui.QPushButton(self.actionsTab1)
        self.stopServerJob.setEnabled(False)
        self.stopServerJob.setObjectName(_fromUtf8("stopServerJob"))
        self.horizontalLayout_3.addWidget(self.stopServerJob)
        self.removeServerJob = QtGui.QPushButton(self.actionsTab1)
        self.removeServerJob.setEnabled(False)
        self.removeServerJob.setObjectName(_fromUtf8("removeServerJob"))
        self.horizontalLayout_3.addWidget(self.removeServerJob)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.newServerJob = QtGui.QPushButton(self.actionsTab1)
        self.newServerJob.setObjectName(_fromUtf8("newServerJob"))
        self.horizontalLayout_3.addWidget(self.newServerJob)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridTabWidget.addTab(self.actionsTab1, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.gridTabWidget)
        self.stackedWidget.addWidget(self.gridPage)
        self.nothingPage = QtGui.QWidget()
        self.nothingPage.setObjectName(_fromUtf8("nothingPage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.nothingPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.nothingPage)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.nothingPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName(_fromUtf8("menuPlik"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setStatusTip(_fromUtf8(""))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.menuPlik.addAction(self.actionConnect)
        self.menuPlik.addAction(self.actionDisconnect)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionExit)
        self.menubar.addAction(self.menuPlik.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.clientTabWidget.setCurrentIndex(0)
        self.gridTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IdleGrid Administration Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Informacje o kliencie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Wersja:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientVersion.setText(QtGui.QApplication.translate("MainWindow", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Identyfikator:", None, QtGui.QApplication.UnicodeUTF8))
        self.machineId.setText(QtGui.QApplication.translate("MainWindow", "machineId", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Numer sesji:", None, QtGui.QApplication.UnicodeUTF8))
        self.sessionId.setText(QtGui.QApplication.translate("MainWindow", "sessionId", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.system.setText(QtGui.QApplication.translate("MainWindow", "system", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Nazwa komputera:", None, QtGui.QApplication.UnicodeUTF8))
        self.node.setText(QtGui.QApplication.translate("MainWindow", "node", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Wydanie:", None, QtGui.QApplication.UnicodeUTF8))
        self.release.setText(QtGui.QApplication.translate("MainWindow", "release", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Wersja", None, QtGui.QApplication.UnicodeUTF8))
        self.version.setText(QtGui.QApplication.translate("MainWindow", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Architektura:", None, QtGui.QApplication.UnicodeUTF8))
        self.machine.setText(QtGui.QApplication.translate("MainWindow", "machine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Procesor:", None, QtGui.QApplication.UnicodeUTF8))
        self.processor.setText(QtGui.QApplication.translate("MainWindow", "processor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Zasoby", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Wolna pamięć:", None, QtGui.QApplication.UnicodeUTF8))
        self.memoryFree.setText(QtGui.QApplication.translate("MainWindow", "memoryFree", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Pamięć dostępna:", None, QtGui.QApplication.UnicodeUTF8))
        self.totalMemory.setText(QtGui.QApplication.translate("MainWindow", "totalMemory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Użycie procesora:", None, QtGui.QApplication.UnicodeUTF8))
        self.cpuUsage.setText(QtGui.QApplication.translate("MainWindow", "cpuUsage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Wolne miejsce na /:", None, QtGui.QApplication.UnicodeUTF8))
        self.diskFree.setText(QtGui.QApplication.translate("MainWindow", "diskFree", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Aktualny czas:", None, QtGui.QApplication.UnicodeUTF8))
        self.actualTime.setText(QtGui.QApplication.translate("MainWindow", "actualTime", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTabWidget.setTabText(self.clientTabWidget.indexOf(self.infoTab), QtGui.QApplication.translate("MainWindow", "Informacje", None, QtGui.QApplication.UnicodeUTF8))
        self.jobsClientList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Identyfikator", None, QtGui.QApplication.UnicodeUTF8))
        self.jobsClientList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.startClientJob.setText(QtGui.QApplication.translate("MainWindow", "Uruchom", None, QtGui.QApplication.UnicodeUTF8))
        self.stopClientJob.setText(QtGui.QApplication.translate("MainWindow", "Zatrzymaj", None, QtGui.QApplication.UnicodeUTF8))
        self.removeClientJob.setText(QtGui.QApplication.translate("MainWindow", "Usuń", None, QtGui.QApplication.UnicodeUTF8))
        self.newClientJob.setText(QtGui.QApplication.translate("MainWindow", "Nowe", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTabWidget.setTabText(self.clientTabWidget.indexOf(self.jobsTab), QtGui.QApplication.translate("MainWindow", "Zadania", None, QtGui.QApplication.UnicodeUTF8))
        self.closeClient.setText(QtGui.QApplication.translate("MainWindow", "Zamknij klienta", None, QtGui.QApplication.UnicodeUTF8))
        self.shutdownClient.setText(QtGui.QApplication.translate("MainWindow", "Wyłącz komputer klienta", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTabWidget.setTabText(self.clientTabWidget.indexOf(self.actionsTab), QtGui.QApplication.translate("MainWindow", "Akcje", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Informacje o połączeniu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Serwer:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverHost.setText(QtGui.QApplication.translate("MainWindow", "serverHost", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Ilość klientów", None, QtGui.QApplication.UnicodeUTF8))
        self.clientCount.setText(QtGui.QApplication.translate("MainWindow", "clientCount", None, QtGui.QApplication.UnicodeUTF8))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.info), QtGui.QApplication.translate("MainWindow", "Informacje", None, QtGui.QApplication.UnicodeUTF8))
        self.serverJobList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Identyfikator", None, QtGui.QApplication.UnicodeUTF8))
        self.serverJobList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.startServerJob.setText(QtGui.QApplication.translate("MainWindow", "Uruchom", None, QtGui.QApplication.UnicodeUTF8))
        self.stopServerJob.setText(QtGui.QApplication.translate("MainWindow", "Zatrzymaj", None, QtGui.QApplication.UnicodeUTF8))
        self.removeServerJob.setText(QtGui.QApplication.translate("MainWindow", "Usuń", None, QtGui.QApplication.UnicodeUTF8))
        self.newServerJob.setText(QtGui.QApplication.translate("MainWindow", "Nowe", None, QtGui.QApplication.UnicodeUTF8))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.actionsTab1), QtGui.QApplication.translate("MainWindow", "Zadania", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Brak połączenia", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlik.setTitle(QtGui.QApplication.translate("MainWindow", "Plik", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "&Zakończ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "&Połącz", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconnect.setText(QtGui.QApplication.translate("MainWindow", "&Rozłącz", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconnect.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))

